# Generated by Django 4.0.3 on 2022-04-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_post_hello'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hello',
            new_name='title',
        ),
    ]
